{
    "Table": {
        "Name": "cdkdl_dev_foundationstoragef3_s3bucketraw88473b86_cxz3i1e716d3",
        "DatabaseName": "cdkdl-dev",
        "Owner": "owner",
        "CreateTime": datetime.datetime(2021, 11, 15, 7, 38, 22, tzinfo=tzlocal()),
        "UpdateTime": datetime.datetime(2021, 11, 15, 7, 38, 22, tzinfo=tzlocal()),
        "LastAccessTime": datetime.datetime(2021, 11, 15, 7, 38, 22, tzinfo=tzlocal()),
        "Retention": 0,
        "StorageDescriptor": {
            "Columns": [
                {"Name": "vendorid", "Type": "bigint"},
                {"Name": "lpep_pickup_datetime", "Type": "string"},
                {"Name": "lpep_dropoff_datetime", "Type": "string"},
                {"Name": "store_and_fwd_flag", "Type": "string"},
                {"Name": "ratecodeid", "Type": "bigint"},
                {"Name": "pulocationid", "Type": "bigint"},
                {"Name": "dolocationid", "Type": "bigint"},
                {"Name": "passenger_count", "Type": "bigint"},
                {"Name": "trip_distance", "Type": "double"},
                {"Name": "fare_amount", "Type": "double"},
                {"Name": "extra", "Type": "double"},
                {"Name": "mta_tax", "Type": "double"},
                {"Name": "tip_amount", "Type": "double"},
                {"Name": "tolls_amount", "Type": "double"},
                {"Name": "ehail_fee", "Type": "string"},
                {"Name": "improvement_surcharge", "Type": "double"},
                {"Name": "total_amount", "Type": "double"},
                {"Name": "payment_type", "Type": "bigint"},
                {"Name": "trip_type", "Type": "bigint"},
                {"Name": "congestion_surcharge", "Type": "double"},
            ],
            "Location": "s3://cdkdl-dev-foundationstoragef3-s3bucketraw88473b86-cxz3i1e716d3/",
            "InputFormat": "org.apache.hadoop.mapred.TextInputFormat",
            "OutputFormat": "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat",
            "Compressed": False,
            "NumberOfBuckets": -1,
            "SerdeInfo": {
                "SerializationLibrary": "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe",
                "Parameters": {"field.delim": ","},
            },
            "BucketColumns": [],
            "SortColumns": [],
            "Parameters": {
                "CrawlerSchemaDeserializerVersion": "1.0",
                "CrawlerSchemaSerializerVersion": "1.0",
                "UPDATED_BY_CRAWLER": "crawlerraw-k5DIcIH9II8T",
                "areColumnsQuoted": "false",
                "averageRecordSize": "153",
                "classification": "csv",
                "columnsOrdered": "true",
                "compressionType": "none",
                "delimiter": ",",
                "objectCount": "1",
                "recordCount": "37183",
                "sizeKey": "5689051",
                "skip.header.line.count": "1",
                "typeOfData": "file",
            },
            "StoredAsSubDirectories": False,
        },
        "PartitionKeys": [{"Name": "partition_0", "Type": "string"}],
        "TableType": "EXTERNAL_TABLE",
        "Parameters": {
            "CrawlerSchemaDeserializerVersion": "1.0",
            "CrawlerSchemaSerializerVersion": "1.0",
            "UPDATED_BY_CRAWLER": "crawlerraw-k5DIcIH9II8T",
            "areColumnsQuoted": "false",
            "averageRecordSize": "153",
            "classification": "csv",
            "columnsOrdered": "true",
            "compressionType": "none",
            "delimiter": ",",
            "objectCount": "1",
            "recordCount": "37183",
            "sizeKey": "5689051",
            "skip.header.line.count": "1",
            "typeOfData": "file",
        },
        "CreatedBy": "arn:aws:sts::820406222077:assumed-role/cdkdl-dev-batchglueBB9040D3-crawlerrole40EA2665-YAX8ADPUTE9S/AWS-Crawler",
        "IsRegisteredWithLakeFormation": False,
        "CatalogId": "820406222077",
    },
    "ResponseMetadata": {
        "RequestId": "aa189be6-5d68-44c4-8d9a-a862f829cdab",
        "HTTPStatusCode": 200,
        "HTTPHeaders": {
            "date": "Mon, 15 Nov 2021 10:19:41 GMT",
            "content-type": "application/x-amz-json-1.1",
            "content-length": "2612",
            "connection": "keep-alive",
            "x-amzn-requestid": "aa189be6-5d68-44c4-8d9a-a862f829cdab",
        },
        "RetryAttempts": 0,
    },
}
